export const CONTRACT_REPOSITORY = Symbol('CONTRACT_REPOSITORY');
export const DEMO_CONTRACT_SEEDS = Symbol('DEMO_CONTRACT_SEEDS');
export const OVERDUE_SCHEDULER_ENABLED = Symbol('OVERDUE_SCHEDULER_ENABLED');
