import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve, sep } from 'node:path';
import { DomainError } from '../errors/domain.error.js';
import type { PrivateFileStore, StoredFile } from './file-store.types.js';
import { contentTypeForKey } from './image-signature.js';

const SAFE_KEY = /^[A-Za-z0-9][A-Za-z0-9/_.-]*$/;
const MISSING_FILE = 'ENOENT';

function isMissing(error: unknown): boolean {
  return (error as NodeJS.ErrnoException | null)?.code === MISSING_FILE;
}

/** Single-replica default under `PRIVATE_FILE_DIR`; object storage replaces it behind the same port. */
export class DiskFileStore implements PrivateFileStore {
  private readonly root: string;

  constructor(root: string) {
    this.root = resolve(root);
  }

  async get(objectKey: string): Promise<StoredFile | null> {
    try {
      const bytes = await readFile(this.pathFor(objectKey));
      return { bytes, contentType: contentTypeForKey(objectKey) };
    } catch (error) {
      if (isMissing(error)) return null;
      throw error;
    }
  }

  async put(objectKey: string, bytes: Buffer): Promise<void> {
    const path = this.pathFor(objectKey);
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, bytes);
  }

  /** Keys are generated by the API, but a traversal attempt still never leaves the root. */
  private pathFor(objectKey: string): string {
    const segments = objectKey.split('/');
    if (!SAFE_KEY.test(objectKey) || segments.includes('..') || segments.includes('.')) {
      throw new DomainError('INVALID_INPUT', 'Khóa tệp không hợp lệ');
    }
    const path = resolve(this.root, objectKey);
    if (!path.startsWith(this.root + sep)) {
      throw new DomainError('INVALID_INPUT', 'Khóa tệp không hợp lệ');
    }
    return path;
  }
}
